version: '3'

services:
  sqlserversrv:
    container_name: sqlserversrv
    image: microsoft/mssql-server-linux:latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=root
      - MSSQL_PID=Express
    #volumes:
      #- ~/docker-volumes/sqlsrv:/var/opt/mssql
      # /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'TestPassWord1234'
    ports:
      - "1433:1433"
    network_mode: "bridge"

  mongosrv:
    container_name: mongosrv
    image: mongo:latest
    ports:
      - "27017:27017"
    network_mode: "bridge"

  lumenapp:
    container_name: lumenapp
    image: jgcl88/alpine-nginx-php:latest
    command: ["sh", "-c", "composer install && php artisan migrate && /docker/start.sh"]
    depends_on:
      - sqlserversrv
      - mongosrv
    links:
      - sqlserversrv
      - mongosrv
    volumes:
      - ./application:/app
    ports:
      - "80:80"
    network_mode: "bridge"
